- name: Hello World Sample
  hosts: localhost
  # roles:
  #   - "david.dep_test.my_role"

  tasks:
    - name: Gather some real Facts.
      galaxy.collection_demo.real_facts:
        name: John Snow
      register: testout

    - debug:
        msg: "{{ testout }}"
